name: Dual Runner Heavy Benchmark

on:
  push:
    branches: ["**"]

jobs:
  benchmark:
    name: Full Heavy Benchmark on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - self-hosted

    steps:
      - name: System Info
        run: |
          echo "Runner: ${{ matrix.runner }}"
          lscpu
          echo "vCPUs: $(nproc)"
          free -h
          df -h

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y sysbench speedtest-cli

      - name: Heavy CPU Test
        run: |
          sysbench cpu --cpu-max-prime=100000 --threads=$(nproc) run

      - name: Heavy RAM Test
        run: |
          sysbench memory --memory-total-size=12G --threads=$(nproc) run

      - name: Heavy Disk I/O Test
        run: |
          sysbench fileio --file-total-size=5G --file-test-mode=seqrd prepare
          sysbench fileio --file-total-size=5G --file-test-mode=seqrd --time=30 --threads=$(nproc) --max-requests=0 run
          sysbench fileio --file-total-size=5G --file-test-mode=seqrd cleanup

      - name: Network Speed Test
        run: |
          speedtest-cli --secure --simple
