name: Axon Framework

on:
  push:
    branches:
      - main
      - master
      - axon-*.*.x
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: Test and Build on JDK ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        include:
          - java-version: 8
            sonar-enabled: false
            deploy-enabled: false
          - java-version: 11
            sonar-enabled: false
            deploy-enabled: false
          - java-version: 17
            sonar-enabled: false
            deploy-enabled: false
          - java-version: 21
            sonar-enabled: false
            deploy-enabled: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          cache: "maven"
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Regular Build
        if: ${{ !matrix.sonar-enabled }}
        run: |
          ./mvnw -B -U -Dstyle.color=always -Possrh -Pintegration-test -Djacoco.skip=true -Dsurefire.rerunFailingTestsCount=5 clean verify
